### ISSUE TITLE
Feature question: callback function

### ISSUE THREAD

**Issue by donboyd5** [m3g/SPGBox.jl#17]
Hi. Thank you for this excellent package. It is extremely fast and accurate on a relatively large-scale problem I have (300k variables, bounds, twice-differentiable objective function, using ReverseDiff). I have found it to perform better than CCSAQ and LBFGS in NLOpt, which appear to be my best alternatives to SPGBox.

In my problem, I am looking for "good enough" solutions - defined based on complex combinations of variables I would like to calculate at each iteration. It would be really great if SPGBox allowed creation of a user-defined callback function that I could use to (1) calculate these variables, (2) report on them at every kth iteration, and (3) send a termination code back to SPGBox if my criteria are met. This would be similar to what the [Optimization package](https://github.com/SciML/Optimization.jl) allows. (And it would be really neat if they would incorporate the ability to use SPGBox from within Optimization.)  It looks (?) like the call to the callback function would be right after line 255 in [spgbox_main.jl](https://github.com/m3g/SPGBox.jl/blob/main/src/spgbox_main.jl).

Do you have any plans to add a callback feature?

Many thanks.

Don

**Comment by lmiq** [comment]
Thank you for your feedback. 

I do plan to make it work with the higher level optimization packages. I just didn't have the time to work on that.

Concerning the call back, that seems a rather simple addition, given that we already support a fully in-place calculation.

I can try implementing that, but currently I'm quite busy. 

We are open for contributions, of course, and I'll be happy to help if someone wants to give it a try.

**Comment by lmiq** [comment]
Actually after some thought I found that it was fairly easy to implement the callback, and I've given it a try.

You can install the trial version with:

```julia
import Pkg; Pkg.add(url="https://github.com/m3g/SPGBox.jl", rev="callback")
```

Then, this is one example of how to use it:

```julia
julia> using SPGBox

julia> f(x) = x[1]^2 + (x[2] - 1)^2
f (generic function with 1 method)

julia> function g!(g, x)
           g[1] = 2 * x[1]
           g[2] = 2 * (x[2] - 1)
       end
g! (generic function with 1 method)

julia> function my_callback(R::SPGBoxResult)
           if R.nit <= 1
               return false 
           else
               return true
           end
       end
my_callback (generic function with 1 method)

julia> x = [10.0, 18.0]
2-element Vector{Float64}:
 10.0
 18.0

julia> R = spgbox!(f, g!, x; callback = my_callback)

 SPGBOX RESULT: 

 Convergence achieved. 

 Final objective function value = 388.99999931805274
 Sample of best point = Vector{Float64}[ 9.999999991234612, 17.99999998509884]
 Projected gradient norm = 33.99999997019768

 Number of iterations = 2
 Number of function evaluations = 2
```

The function `my_callback` has as input the `SPGBoxResult` structure (explained [here](https://m3g.github.io/SPGBox.jl/stable/usage/#Result-data-structure-and-possible-outcomes)), and must return `true` or `false`. If `true`, spgbox will return immediately with the current point.

If you don't mind testing this interface a bit, I will then release it as a new version.

**Comment by lmiq** [comment]
I've released a 0.6.0 version with this implemented. I made some other changes, improved docs, etc, so I decided to move this forward. I'll close the issue here, but if the implemented function doesn't addresses your issue, please feel free to reopen it.

There were some breaking changes in the release, but they are mostly not noticeable (in particular, upper and lower bounds have to be provided as keyword arguments - which was the documented version - positional arguments are not accepted anymore).

Version 0.6.0 should be available at any moment, and the docs will include the callback documentation.

**Comment by donboyd5** [comment]
Thank you! I'll be using it over the next several days so I'll give you some feedback then. Fantastic!

**Comment by donboyd5** [comment]
Hi again. Thank you very much for the callback feature.

I was wondering whether there is a way, in the callback function, to access variables created in the objective function that in turn used data that was in the calling environment. If so, that would be very useful to me, if not it is still great to have a callback function that has access to the values in SPGBoxResult.

Many thanks.

**Comment by lmiq** [comment]
The callback function can be a closure, like what is described here for the main function:

https://m3g.github.io/SPGBox.jl/stable/usage/#Data-dependent-function-evaluation

You can define something like:

```
callback(R) = f(R, data...)
```

Where `data` is any data you need. I'm on the phone now, so I'm sorry not providing a better example. Please let me know of any difficulties.

**Comment by donboyd5** [comment]
Got it! Thank you!

Don
