### ISSUE TITLE
Make the API consistent with Optim.jl

### ISSUE THREAD

**Issue by rht** [m3g/SPGBox.jl#2]
Currently:
1. The function signature for the gradient is `spg_g!(x, g)`, instead of Optim.jl's `g!(g, x)`
2. `spgbox!` uses cryptic argument names such as l for lower bound, u for upper bound
3. `spgbox!`'s first argument is the initial guess instead of the objective function

**Comment by lmiq** [comment]
Done in version 0.2.0 to be released at any moment. 

Please let me know if anything else can be done to improve interoperability.
