### ISSUE TITLE
Document that the initial guess x0 is mutated during and after optimization

### ISSUE THREAD

**Issue by rht** [m3g/SPGBox.jl#3]
Either document the mutating x0, or maybe create a copy of x0 inside the function `spgbox!` which becomes the final answer?

**Comment by lmiq** [comment]
Version 0.3.1 to be released at any moment will contain a `spgbox` version (without the `!`) which performs the copy of the input array and, thus, does not mutate it. The documentation is updated. (using the version that mutates is probably the most reasonable option most of the time).
